# TODO - change scripts to point to project folder

stages:
  - development
  - staging
  - production

development:
  stage: development
  script:
    - echo "Deploying development"
    - cd /home/ubuntu/PROJECTDIR/development/web.client.js
    - sudo git pull origin development
    - sudo docker-compose up --force-recreate
    - echo "Done deploying development"
  only:
    - development

staging:
  stage: staging
  script:
    - echo "Deploying staging"
    - cd /home/ubuntu/PROJECTDIR/staging/web.client.js
    - sudo git pull origin staging
    - sudo docker-compose up --force-recreate
    - echo "Done deploying staging"
  only:
    - staging

production:
  stage: production
  script:
    - echo "Deploying production"
    - cd /home/ubuntu/PROJECTDIR/production/web.client.js
    - sudo git pull origin production
    - sudo docker-compose up --force-recreate
    - echo "Done deploying production"
  only:
    - production
